### ISSUE TITLE
Exception:  Braintree: illegal argument exception  java.lang.IllegalArgumentException: illegal object in getInstance: com.braintree.org.bouncycastle.asn1.DERSequence

### ISSUE THREAD

**Issue by mnchiu** [braintree/braintree_android_encryption#9]
We're running into the same issue as https://github.com/braintree/braintree_android_encryption/issues/8.

The exception stack-trace is 

`
07-24 18:08:24.657 801-801/com.gnc.android E/PredictSpring_PaymentCardActivity: Braintree: illegal argument exception
    java.lang.IllegalArgumentException: illegal object in getInstance: com.braintree.org.bouncycastle.asn1.DERSequence
        at com.braintree.org.bouncycastle.asn1.DERInteger.getInstance(DERInteger.java:26)
        at com.braintree.org.bouncycastle.asn1.x509.RSAPublicKeyStructure.<init>(RSAPublicKeyStructure.java:62)
        at com.braintree.org.bouncycastle.asn1.x509.RSAPublicKeyStructure.getInstance(RSAPublicKeyStructure.java:37)
        at com.braintreegateway.encryption.Rsa.publicKey(Rsa.java:53)
        at com.braintreegateway.encryption.Rsa.encrypt(Rsa.java:29)
        at com.braintreegateway.encryption.Braintree.encrypt(Braintree.java:18)
`

I ran through the mentioned comments in the issue above and the test key works, but ours does not.  Was there a resolution issue 8 had?

**Comment by quinnjn** [comment]
Unfortunately this integration pattern is pretty old. The last commit to this repository was October 2015. 

Is there a specific reason you still need to use Client Side Encryption as your Braintree integration? We'd recommend moving to the [Braintree Android SDK](https://github.com/braintree/braintree_android). 

Here is an easy guide to get started: https://developers.braintreepayments.com/start/hello-client/android/v2

**Comment by mnchiu** [comment]
A client of ours is using this particular integration and we cannot make the switch easily.  Is there anyway we can retrieve the public key and private key from the braintree dashboard?  Is there any further information you may provide to help us solve this issue?

**Comment by quinnjn** [comment]
Yes you can retrieve the [API keys from the Braintree Control Panel](https://articles.braintreepayments.com/control-panel/important-gateway-credentials#api-keys). 

If you need additional contextual help with the Control Panel you can reach out to Braintree support: https://developers.braintreepayments.com/forms/contact

We'll update the README to reflect that this repository is deprecated.
